import { Inter } from "next/font/google";
import "./globals.css";
import favIcon from '@/app/assets/images/logo.png'

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "FOODSI",
  description: "Generated by create next app",
  icons: [
    {
      rel: "icon",
      url: favIcon,
      sizes: "32x32",
      type: "image/png",
    },
  ],
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
